/*
 * Tencent is pleased to support the open source community by making wechat-matrix available.
 * Copyright (C) 2018 THL A29 Limited, a Tencent company. All rights reserved.
 * Licensed under the BSD 3-Clause License (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://opensource.org/licenses/BSD-3-Clause
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.kernelflux.traceharbor.resource.analyzer

import com.kernelflux.traceharbor.resource.analyzer.model.ActivityLeakResult
import com.kernelflux.traceharbor.resource.analyzer.model.AndroidExcludedBmpRefs
import com.kernelflux.traceharbor.resource.analyzer.model.AndroidExcludedRefs
import com.kernelflux.traceharbor.resource.analyzer.model.DuplicatedBitmapResult
import com.kernelflux.traceharbor.resource.analyzer.model.DuplicatedBitmapResult.DuplicatedBitmapEntry
import com.kernelflux.traceharbor.resource.analyzer.model.ExcludedBmps
import com.kernelflux.traceharbor.resource.analyzer.model.ExcludedRefs
import com.kernelflux.traceharbor.resource.analyzer.model.HeapSnapshot
import com.kernelflux.traceharbor.resource.analyzer.model.HprofBitmapProvider
import com.kernelflux.traceharbor.resource.analyzer.utils.BitmapDecoder
import com.kernelflux.traceharbor.resource.common.utils.StreamUtil
import org.apache.commons.cli.CommandLine
import org.apache.commons.cli.DefaultParser
import org.apache.commons.cli.HelpFormatter
import org.apache.commons.cli.MissingOptionException
import org.apache.commons.cli.Option
import org.apache.commons.cli.Options
import org.apache.commons.cli.ParseException
import org.json.JSONObject
import java.awt.image.BufferedImage
import java.io.BufferedOutputStream
import java.io.BufferedReader
import java.io.BufferedWriter
import java.io.File
import java.io.FileOutputStream
import java.io.FileWriter
import java.io.IOException
import java.io.InputStreamReader
import java.io.OutputStream
import java.io.PrintStream
import java.io.PrintWriter
import java.util.EnumSet
import java.util.HashMap
import java.util.zip.ZipEntry
import java.util.zip.ZipFile
import java.util.zip.ZipOutputStream
import javax.imageio.ImageIO

/**
 * Created by tangyinsheng on 2017/7/3.
 */
class CLIMain private constructor() {

    @Suppress("unused")
    enum class AnalyzerOptions {
        OPTION_INPUT {
            override fun build(): Option {
                return Option.builder("i")
                    .longOpt("input")
                    .desc("Required. Path to read result generated by resource canary module.")
                    .numberOfArgs(1)
                    .argName("inputPath")
                    .optionalArg(false)
                    .required(true)
                    .build()
            }
        },
        OPTION_OUTPUT {
            override fun build(): Option {
                return Option.builder("o")
                    .longOpt("output")
                    .desc("Required. Path to store analyze result directory.")
                    .numberOfArgs(1)
                    .argName("outputPath")
                    .optionalArg(false)
                    .required(true)
                    .build()
            }
        },
        OPTION_COMPRESS_OUTPUT {
            override fun build(): Option {
                return Option.builder("co")
                    .longOpt("compress-output")
                    .desc("Optional. Compress analyze result as a zip.")
                    .required(false)
                    .build()
            }
        },
        OPTION_MIN_BMPLEAK_SIZE {
            override fun build(): Option {
                return Option.builder("mb")
                    .longOpt("min-bmpleak-size")
                    .desc(
                        "Optional. Minimum size of accepted bmp leak." +
                            " Any leaks whose size is less than that would be ignored.",
                    )
                    .numberOfArgs(1)
                    .argName("minBmpLeakSize")
                    .optionalArg(false)
                    .required(false)
                    .build()
            }
        },
        OPTION_HELP {
            override fun build(): Option {
                return Option.builder("h")
                    .longOpt("help")
                    .desc("Optional. Show this message.")
                    .required(false)
                    .build()
            }
        },
        ;

        lateinit var mOption: Option
        abstract fun build(): Option

        companion object {
            @JvmStatic
            fun buildAll(): Options {
                val options = Options()
                for (builder in EnumSet.allOf(AnalyzerOptions::class.java)) {
                    val option = builder.build()
                    builder.mOption = option
                    options.addOption(option)
                }
                return options
            }
        }
    }

    companion object {
        private const val ERROR_SUCCESS = 0
        private const val ERROR_MISSING_INPUT_PATH = -1
        private const val ERROR_NEED_ARGUMENTS = -2
        private const val ERROR_MISSING_OUTPUT_PATH = -3
        private const val ERROR_OTHERS = -255

        private var mInputFile: File? = null
        private var mOutputFile: File? = null
        private var mCompressOutput = false
        private var mMinBmpLeakSize = 5000

        private const val EXTRA_INFO_NAME = "extra.info"

        private val sOptions: Options = AnalyzerOptions.buildAll()

        private fun printUsage(out: PrintStream) {
            val pw = PrintWriter(out)
            pw.println("TraceHarbor ResourceCanary CommandLine Tools.\n")
            val formatter = HelpFormatter()
            formatter.optionComparator = null
            formatter.printUsage(pw, 120, "java -jar analyzer.jar", sOptions)
            pw.println("\noptions:")
            formatter.printOptions(pw, 120, sOptions, 0, 4)
            pw.flush()
        }

        @Throws(ParseException::class)
        private fun parseArguments(cmdline: CommandLine) {
            val inputPath = cmdline.getOptionValue(AnalyzerOptions.OPTION_INPUT.mOption.longOpt)!!
            mInputFile = File(inputPath)

            if (cmdline.hasOption(AnalyzerOptions.OPTION_COMPRESS_OUTPUT.mOption.longOpt)) {
                mCompressOutput = true
            }

            var outputPath = cmdline.getOptionValue(AnalyzerOptions.OPTION_OUTPUT.mOption.longOpt)!!
            if (mCompressOutput && !outputPath.endsWith(".zip") && !outputPath.endsWith(".jar")) {
                outputPath += ".zip"
            }
            mOutputFile = File(outputPath)

            val minBmpLeakSizeVal =
                cmdline.getOptionValue(AnalyzerOptions.OPTION_MIN_BMPLEAK_SIZE.mOption.longOpt)
            if (minBmpLeakSizeVal != null) {
                mMinBmpLeakSize = minBmpLeakSizeVal.toInt()
            }
        }

        @Throws(IOException::class)
        private fun doAnalyze() {
            var zf: ZipFile? = null
            var br: BufferedReader? = null
            var tempHprofFile: File? = null
            try {
                val inputFile = mInputFile ?: throw IllegalStateException("Input file is not set.")
                val zipFile = ZipFile(inputFile)
                zf = zipFile
                val canaryResultInfoEntry =
                    zipFile.getEntry("result.info")
                        ?: throw IllegalStateException("result.info is absent in input archive.")
                val resultInfoMap = HashMap<String, String>()
                val resultInfoReader =
                    BufferedReader(InputStreamReader(zipFile.getInputStream(canaryResultInfoEntry)))
                br = resultInfoReader
                while (true) {
                    val confLine = resultInfoReader.readLine() ?: break
                    if (confLine.startsWith("#")) {
                        // Skip comment.
                        continue
                    }
                    val kvPair = confLine.split("\\s*=\\s*".toRegex())
                    if (kvPair.size != 2) {
                        // Skip bad config line.
                        continue
                    }
                    val key = kvPair[0].trim()
                    val value = kvPair[1].trim()
                    resultInfoMap[key] = value
                }

                val sdkVersionStr = resultInfoMap["sdkVersion"]
                    ?: throw IllegalStateException("sdkVersion is absent in result.info.")
                val sdkVersion = sdkVersionStr.toInt()

                val manufacturer = resultInfoMap["manufacturer"]
                    ?: throw IllegalStateException("manufacturer is absent in result.info.")

                val hprofEntryName = resultInfoMap["hprofEntry"]
                    ?: throw IllegalStateException("hprofEntry is absent in result.info.")
                val hprofEntry =
                    zipFile.getEntry(hprofEntryName)
                        ?: throw IllegalStateException("hprof entry '$hprofEntryName' is absent in archive.")

                val leakedActivityKey = resultInfoMap["leakedActivityKey"]
                    ?: throw IllegalStateException("leakedActivityKey is absent in result.info.")

                // We would extract hprof entry into a temporary file.
                tempHprofFile =
                    File(File("").absoluteFile, "temp_${System.currentTimeMillis()}.hprof")
                StreamUtil.extractZipEntry(zipFile, hprofEntry, tempHprofFile)

                // Parse extra info if exists.
                val extraInfo = JSONObject()
                val extraInfoEntry = zipFile.getEntry(EXTRA_INFO_NAME)
                if (extraInfoEntry != null) {
                    var br2: BufferedReader? = null
                    try {
                        val extraInfoReader =
                            BufferedReader(InputStreamReader(zipFile.getInputStream(extraInfoEntry)))
                        br2 = extraInfoReader
                        while (true) {
                            val line = extraInfoReader.readLine() ?: break
                            if (line.startsWith("#")) {
                                // Skip comment.
                                continue
                            }
                            val pair = line.split("\\s*=\\s*".toRegex())
                            if (pair.size < 2) {
                                throw IllegalStateException("bad extra info line: $line")
                            }
                            val key = pair[0].trim()
                            val value = pair[1].trim()
                            extraInfo.put(key, value)
                        }
                    } finally {
                        StreamUtil.closeQuietly(br2)
                    }
                }

                // Then do analyzing works and output into directory or zip according to the option.
                // Besides, store extra info into the result json by the way.
                analyzeAndStoreResult(
                    tempHprofFile!!,
                    sdkVersion,
                    manufacturer,
                    leakedActivityKey,
                    extraInfo,
                )
            } finally {
                if (tempHprofFile != null) {
                    tempHprofFile.delete()
                }
                StreamUtil.closeQuietly(br)
                StreamUtil.closeQuietly(zf)
            }
        }

        @Throws(IOException::class)
        private fun analyzeAndStoreResult(
            hprofFile: File,
            sdkVersion: Int,
            manufacturer: String,
            leakedActivityKey: String,
            extraInfo: JSONObject?,
        ) {
            val heapSnapshot = HeapSnapshot(hprofFile)
            val excludedRefs: ExcludedRefs =
                AndroidExcludedRefs.createAppDefaults(sdkVersion, manufacturer).build()
            val activityLeakResult: ActivityLeakResult =
                ActivityLeakAnalyzer(leakedActivityKey, excludedRefs).analyze(heapSnapshot)

            var duplicatedBmpResult = DuplicatedBitmapResult.noDuplicatedBitmap(0)
            if (sdkVersion < 26) {
                val excludedBmps: ExcludedBmps = AndroidExcludedBmpRefs.createDefaults().build()
                duplicatedBmpResult =
                    DuplicatedBitmapAnalyzer(mMinBmpLeakSize, excludedBmps).analyze(heapSnapshot)
            } else {
                System.err.println(
                    "\n ! SDK version of target device is larger or equal to 26, " +
                        "which is not supported by DuplicatedBitmapAnalyzer.",
                )
            }
            val resultJsonName = "result.json"
            val bufferContentsRootDirName = "buffer_contents"
            val extralInfoKey = "extraInfo"
            if (mCompressOutput) {
                var zos: ZipOutputStream? = null
                try {
                    val outputFile =
                        mOutputFile ?: throw IllegalStateException("Output file is not set.")
                    val zipOut = ZipOutputStream(BufferedOutputStream(FileOutputStream(outputFile)))
                    zos = zipOut
                    val analyzeResultEntry = ZipEntry(resultJsonName)
                    zipOut.putNextEntry(analyzeResultEntry)
                    try {
                        val pw = PrintWriter(zipOut)
                        val resultJson = JSONObject()
                        val activityLeakResultJson = JSONObject()
                        activityLeakResult.encodeToJSON(activityLeakResultJson)
                        val duplicatedBmpResultJson = JSONObject()
                        duplicatedBmpResult.encodeToJSON(duplicatedBmpResultJson)

                        resultJson.put("activityLeakResult", activityLeakResultJson)
                            .put("duplicatedBitmapResult", duplicatedBmpResultJson)

                        if (extraInfo != null && extraInfo.length() > 0) {
                            resultJson.put(extralInfoKey, extraInfo)
                        }

                        pw.println(resultJson.toString())
                        pw.flush()
                    } finally {
                        try {
                            zipOut.closeEntry()
                        } catch (_: Throwable) {
                            // Ignored.
                        }
                    }

                    // Store bitmap buffer.
                    val duplicatedBmpEntries: List<DuplicatedBitmapEntry> =
                        duplicatedBmpResult.getDuplicatedBitmapEntries()
                    val duplicatedBmpEntryCount = duplicatedBmpEntries.size
                    for (i in 0 until duplicatedBmpEntryCount) {
                        val entry = duplicatedBmpEntries[i]
                        val img: BufferedImage = BitmapDecoder.getBitmap(
                            HprofBitmapProvider(entry.getBuffer(), entry.getWidth(), entry.getHeight()),
                        )
                        // Since bmp format is not compatible with alpha channel, we export buffer as png instead.
                        val pngName = "$bufferContentsRootDirName/${entry.getBufferHash()}.png"
                        try {
                            zipOut.putNextEntry(ZipEntry(pngName))
                            ImageIO.write(img, "png", zipOut)
                            zipOut.flush()
                        } finally {
                            try {
                                zipOut.closeEntry()
                            } catch (_: Throwable) {
                                // Ignored.
                            }
                        }
                    }
                } finally {
                    StreamUtil.closeQuietly(zos)
                }
            } else {
                val outputDir = mOutputFile!!
                if (!outputDir.exists()) {
                    outputDir.mkdirs()
                }
                var resultJsonPW: PrintWriter? = null
                try {
                    val resultJsonFile = File(outputDir, resultJsonName)
                    val resultJsonWriter = PrintWriter(BufferedWriter(FileWriter(resultJsonFile)))
                    resultJsonPW = resultJsonWriter
                    val resultJson = JSONObject()
                    val activityLeakResultJson = JSONObject()
                    activityLeakResult.encodeToJSON(activityLeakResultJson)
                    val duplicatedBmpResultJson = JSONObject()
                    duplicatedBmpResult.encodeToJSON(duplicatedBmpResultJson)

                    resultJson.put("activityLeakResult", activityLeakResultJson)
                        .put("duplicatedBitmapResult", duplicatedBmpResultJson)

                    if (extraInfo != null && extraInfo.length() > 0) {
                        resultJson.put(extralInfoKey, extraInfo)
                    }

                    resultJsonWriter.println(resultJson.toString())
                    resultJsonWriter.flush()
                } finally {
                    StreamUtil.closeQuietly(resultJsonPW)
                }

                // Store bitmap buffer.
                val bufferContentsRootDir = File(outputDir, bufferContentsRootDirName)
                if (!bufferContentsRootDir.exists()) {
                    bufferContentsRootDir.mkdirs()
                }
                val duplicatedBmpEntries: List<DuplicatedBitmapEntry> =
                    duplicatedBmpResult.getDuplicatedBitmapEntries()
                val duplicatedBmpEntryCount = duplicatedBmpEntries.size
                for (i in 0 until duplicatedBmpEntryCount) {
                    val entry = duplicatedBmpEntries[i]
                    val img: BufferedImage = BitmapDecoder.getBitmap(
                        HprofBitmapProvider(entry.getBuffer(), entry.getWidth(), entry.getHeight()),
                    )
                    // Since bmp format is not compatible with alpha channel, we export buffer as png instead.
                    val pngName = "${entry.getBufferHash()}.png"
                    var os: OutputStream? = null
                    try {
                        val pngFile = File(bufferContentsRootDir, pngName)
                        val outputStream = BufferedOutputStream(FileOutputStream(pngFile))
                        os = outputStream
                        ImageIO.write(img, "png", outputStream)
                    } finally {
                        StreamUtil.closeQuietly(os)
                    }
                }
            }
        }

        @JvmStatic
        fun main(args: Array<String>) {
            if (args.isEmpty()) {
                printUsage(System.out)
                System.exit(ERROR_NEED_ARGUMENTS)
            }
            try {
                val cmdline: CommandLine = DefaultParser().parse(sOptions, args)
                if (cmdline.hasOption(AnalyzerOptions.OPTION_HELP.mOption.longOpt)) {
                    printUsage(System.out)
                    System.exit(ERROR_SUCCESS)
                }

                parseArguments(cmdline)
                doAnalyze()
                System.exit(ERROR_SUCCESS)
            } catch (e: MissingOptionException) {
                var errCode = ERROR_OTHERS
                System.err.println(e.message)
                val firstMissingOpt = e.missingOptions.iterator().next() as String
                if (AnalyzerOptions.OPTION_INPUT.mOption.opt == firstMissingOpt) {
                    errCode = ERROR_MISSING_INPUT_PATH
                } else if (AnalyzerOptions.OPTION_OUTPUT.mOption.opt == firstMissingOpt) {
                    errCode = ERROR_MISSING_OUTPUT_PATH
                }
                System.exit(errCode)
            } catch (thr: Throwable) {
                thr.printStackTrace()
                System.exit(ERROR_OTHERS)
            }
        }
    }
}
